import { AwsService, AwsServiceConnection } from '@/features/aws/services/libs/types'

export const serviceConnectionsMap: Record<string, AwsServiceConnection> = {
  'iam-role': {
    requiredConnections: [],
    recommendedConnections: ['lambda', 'ec2-instance', 'api-gateway'],
    optionalConnections: [],
  },
  'ec2-instance': {
    requiredConnections: ['subnet'],
    recommendedConnections: ['security-group', 'iam-role', 'elb', 'asg', 'ebs'],
    optionalConnections: ['efs', 's3', 'api-gateway', 'elastic-ip'],
  },
  'elastic-ip': {
    requiredConnections: ['ec2-instance'],
    recommendedConnections: [],
    optionalConnections: ['nat-gateway'],
  },
  ebs: {
    requiredConnections: ['ec2-instance'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  efs: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: ['ec2-instance'],
    optionalConnections: [],
  },
  elb: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: ['ec2-instance', 'asg'],
    optionalConnections: [],
  },
  asg: {
    requiredConnections: ['subnet'],
    recommendedConnections: ['elb', 'ec2-instance'],
    optionalConnections: [],
  },
  rds: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  aurora: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  elasticache: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  s3: {
    requiredConnections: [],
    recommendedConnections: ['cloudfront', 'lambda', 'api-gateway'],
    optionalConnections: [],
  },
  cloudfront: {
    requiredConnections: ['s3'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  sqs: {
    requiredConnections: [],
    recommendedConnections: ['lambda', 'sns'],
    optionalConnections: [],
  },
  sns: {
    requiredConnections: [],
    recommendedConnections: ['sqs', 'lambda'],
    optionalConnections: [],
  },
  kinesis: {
    requiredConnections: [],
    recommendedConnections: ['lambda'],
    optionalConnections: [],
  },
  mq: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  apigw: {
    requiredConnections: ['lambda'],
    recommendedConnections: ['s3'],
    optionalConnections: [],
  },
  lambda: {
    requiredConnections: ['iam-role'],
    recommendedConnections: ['s3', 'sns', 'sqs', 'api-gateway', 'subnet', 'security-group'],
    optionalConnections: [],
  },
  'step-functions': {
    requiredConnections: ['lambda'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  cognito: {
    requiredConnections: [],
    recommendedConnections: ['lambda', 'api-gateway'],
    optionalConnections: [],
  },
  dynamodb: {
    requiredConnections: [],
    recommendedConnections: ['lambda'],
    optionalConnections: [],
  },
  documentdb: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  neptune: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  athena: {
    requiredConnections: ['s3'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  redshift: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  opensearch: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  cloudwatch: {
    requiredConnections: [],
    recommendedConnections: [],
    optionalConnections: ['lambda', 'ec2-instance', 'rds'],
  },
  cloudtrail: {
    requiredConnections: ['s3'],
    recommendedConnections: ['cloudwatch'],
    optionalConnections: [],
  },
  config: {
    requiredConnections: [],
    recommendedConnections: ['s3', 'iam-role'],
    optionalConnections: [],
  },
  kms: {
    requiredConnections: [],
    recommendedConnections: ['s3', 'rds', 'ebs'],
    optionalConnections: [],
  },
  ssm: {
    requiredConnections: [],
    recommendedConnections: ['lambda', 'ec2-instance'],
    optionalConnections: [],
  },
  waf: {
    requiredConnections: ['api-gateway', 'cloudfront'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  vpc: {
    requiredConnections: [],
    recommendedConnections: ['subnet', 'internet-gateway', 'nat-gateway'],
    optionalConnections: [],
  },
  subnet: {
    requiredConnections: ['vpc'],
    recommendedConnections: [],
    optionalConnections: ['ec2-instance', 'rds', 'elb', 'asg', 'nat-gateway'],
  },
  'nat-gateway': {
    requiredConnections: ['subnet'],
    recommendedConnections: [],
    optionalConnections: ['elastic-ip'],
  },
  igw: {
    requiredConnections: ['vpc'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  nacl: {
    requiredConnections: ['vpc'],
    recommendedConnections: [],
    optionalConnections: ['subnet'],
  },
  sg: {
    requiredConnections: ['vpc'],
    recommendedConnections: [],
    optionalConnections: ['ec2-instance', 'rds', 'elb', 'lambda', 'aurora'],
  },

  // connections for extra services (bạn thêm)
  'cloudwatch-logs': {
    requiredConnections: [],
    recommendedConnections: [],
    optionalConnections: [],
  },
  'cloudwatch-metric': {
    requiredConnections: [],
    recommendedConnections: [],
    optionalConnections: [],
  },
  codebuild: {
    requiredConnections: ['iam-role'],
    recommendedConnections: ['s3', 'codepipeline'],
    optionalConnections: [],
  },
  codepipeline: {
    requiredConnections: ['roleArn'], // note: roleArn is property, not id — but for connect maybe to codebuild, codedeploy
    recommendedConnections: ['codebuild', 'codedeploy', 's3'],
    optionalConnections: [],
  },
  codedeploy: {
    requiredConnections: [],
    recommendedConnections: ['codepipeline', 'ec2-instance', 'lambda'],
    optionalConnections: [],
  },
  eventbridge: {
    requiredConnections: [],
    recommendedConnections: ['lambda', 'sns'],
    optionalConnections: [],
  },
  'target-group': {
    requiredConnections: ['vpc'],
    recommendedConnections: ['elb', 'asg'],
    optionalConnections: [],
  },
  'vpc-endpoint': {
    requiredConnections: ['vpc'],
    recommendedConnections: [],
    optionalConnections: [],
  },
  msk: {
    requiredConnections: ['subnet', 'security-group'],
    recommendedConnections: [],
    optionalConnections: [],
  },
}

export const listServices: AwsService[] = [
  {
    id: 'iam-role',
    resourceType: 'AWS::IAM::Role',
    displayName: 'IAM Role',
    requiredProps: ['AssumeRolePolicyDocument'],
    connections: serviceConnectionsMap['iam-role'],
  },
  {
    id: 'ec2-instance',
    resourceType: 'AWS::EC2::Instance',
    displayName: 'EC2 Instance',
    requiredProps: ['ImageId', 'InstanceType'],
    connections: serviceConnectionsMap['ec2-instance'],
  },
  {
    id: 'elastic-ip',
    resourceType: 'AWS::EC2::EIP',
    displayName: 'Elastic IP',
    requiredProps: [],
    connections: serviceConnectionsMap['elastic-ip'],
  },
  {
    id: 'ebs',
    resourceType: 'AWS::EC2::Volume',
    displayName: 'EBS Volume',
    requiredProps: ['AvailabilityZone', 'Size'],
    connections: serviceConnectionsMap['ebs'],
  },
  {
    id: 'efs',
    resourceType: 'AWS::EFS::FileSystem',
    displayName: 'EFS',
    requiredProps: [],
    connections: serviceConnectionsMap['efs'],
  },
  {
    id: 'elb',
    resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    displayName: 'Elastic Load Balancer',
    requiredProps: ['Type'],
    connections: serviceConnectionsMap['elb'],
  },
  {
    id: 'asg',
    resourceType: 'AWS::AutoScaling::AutoScalingGroup',
    displayName: 'Auto Scaling Group',
    requiredProps: ['MinSize', 'MaxSize', 'DesiredCapacity'],
    connections: serviceConnectionsMap['asg'],
  },
  {
    id: 'rds',
    resourceType: 'AWS::RDS::DBInstance',
    displayName: 'RDS Instance',
    requiredProps: ['DBInstanceClass', 'Engine', 'MasterUsername', 'MasterUserPassword'],
    connections: serviceConnectionsMap['rds'],
  },
  {
    id: 'aurora',
    resourceType: 'AWS::RDS::DBCluster',
    displayName: 'Aurora Cluster',
    requiredProps: ['Engine'],
    connections: serviceConnectionsMap['aurora'],
  },
  {
    id: 'elasticache',
    resourceType: 'AWS::ElastiCache::CacheCluster',
    displayName: 'ElasticCache',
    requiredProps: ['Engine', 'CacheNodeType', 'NumCacheNodes'],
    connections: serviceConnectionsMap['elasticache'],
  },
  {
    id: 's3',
    resourceType: 'AWS::S3::Bucket',
    displayName: 'S3 Bucket',
    requiredProps: [],
    connections: serviceConnectionsMap['s3'],
  },
  {
    id: 'cloudfront',
    resourceType: 'AWS::CloudFront::Distribution',
    displayName: 'CloudFront',
    requiredProps: ['Enabled'],
    connections: serviceConnectionsMap['cloudfront'],
  },
  {
    id: 'sqs',
    resourceType: 'AWS::SQS::Queue',
    displayName: 'SQS Queue',
    requiredProps: [],
    connections: serviceConnectionsMap['sqs'],
  },
  {
    id: 'sns',
    resourceType: 'AWS::SNS::Topic',
    displayName: 'SNS Topic',
    requiredProps: [],
    connections: serviceConnectionsMap['sns'],
  },
  {
    id: 'kinesis',
    resourceType: 'AWS::Kinesis::Stream',
    displayName: 'Kinesis Data Stream',
    requiredProps: ['ShardCount'],
    connections: serviceConnectionsMap['kinesis'],
  },
  {
    id: 'mq',
    resourceType: 'AWS::AmazonMQ::Broker',
    displayName: 'Amazon MQ',
    requiredProps: ['EngineType', 'EngineVersion', 'HostInstanceType'],
    connections: serviceConnectionsMap['mq'],
  },
  {
    id: 'apigw',
    resourceType: 'AWS::apigw::RestApi',
    displayName: 'API Gateway',
    requiredProps: ['Name'],
    connections: serviceConnectionsMap['apigw'],
  },
  {
    id: 'lambda',
    resourceType: 'AWS::Lambda::Function',
    displayName: 'Lambda Function',
    requiredProps: ['Handler', 'Runtime'],
    connections: serviceConnectionsMap['lambda'],
  },
  {
    id: 'step-functions',
    resourceType: 'AWS::StepFunctions::StateMachine',
    displayName: 'Step Functions',
    requiredProps: ['DefinitionString', 'RoleArn'],
    connections: serviceConnectionsMap['step-functions'],
  },
  {
    id: 'cognito',
    resourceType: 'AWS::Cognito::UserPool',
    displayName: 'Cognito User Pool',
    requiredProps: ['UserPoolName'],
    connections: serviceConnectionsMap['cognito'],
  },
  {
    id: 'dynamodb',
    resourceType: 'AWS::DynamoDB::Table',
    displayName: 'DynamoDB',
    requiredProps: ['AttributeDefinitions', 'KeySchema', 'BillingMode'],
    connections: serviceConnectionsMap['dynamodb'],
  },
  {
    id: 'documentdb',
    resourceType: 'AWS::DocDB::DBCluster',
    displayName: 'DocumentDB',
    requiredProps: ['EngineVersion'],
    connections: serviceConnectionsMap['documentdb'],
  },
  {
    id: 'neptune',
    resourceType: 'AWS::Neptune::DBCluster',
    displayName: 'Neptune',
    requiredProps: [],
    connections: serviceConnectionsMap['neptune'],
  },
  {
    id: 'athena',
    resourceType: 'AWS::Athena::WorkGroup',
    displayName: 'Athena',
    requiredProps: ['Name'],
    connections: serviceConnectionsMap['athena'],
  },
  {
    id: 'redshift',
    resourceType: 'AWS::Redshift::Cluster',
    displayName: 'Redshift',
    requiredProps: [
      'ClusterType',
      'NodeType',
      'NumberOfNodes',
      'MasterUsername',
      'MasterUserPassword',
    ],
    connections: serviceConnectionsMap['redshift'],
  },
  {
    id: 'opensearch',
    resourceType: 'AWS::OpenSearchService::Domain',
    displayName: 'OpenSearch',
    requiredProps: ['DomainName'],
    connections: serviceConnectionsMap['opensearch'],
  },
  {
    id: 'cloudwatch',
    resourceType: 'AWS::CloudWatch::Alarm',
    displayName: 'CloudWatch',
    requiredProps: ['MetricName', 'Namespace', 'ComparisonOperator', 'Threshold'],
    connections: serviceConnectionsMap['cloudwatch'],
  },
  {
    id: 'cloudtrail',
    resourceType: 'AWS::CloudTrail::Trail',
    displayName: 'CloudTrail',
    requiredProps: ['S3BucketName'],
    connections: serviceConnectionsMap['cloudtrail'],
  },
  {
    id: 'config',
    resourceType: 'AWS::Config::ConfigurationRecorder',
    displayName: 'AWS Config',
    requiredProps: ['RoleARN'],
    connections: serviceConnectionsMap['config'],
  },
  {
    id: 'kms',
    resourceType: 'AWS::KMS::Key',
    displayName: 'KMS Key',
    requiredProps: ['KeyPolicy'],
    connections: serviceConnectionsMap['kms'],
  },
  {
    id: 'ssm',
    resourceType: 'AWS::SSM::Parameter',
    displayName: 'SSM Parameter Store',
    requiredProps: ['Name', 'Type', 'Value'],
    connections: serviceConnectionsMap['ssm'],
  },
  {
    id: 'waf',
    resourceType: 'AWS::WAFv2::WebACL',
    displayName: 'WAF',
    requiredProps: ['Scope', 'DefaultAction'],
    connections: serviceConnectionsMap['waf'],
  },
  {
    id: 'vpc',
    resourceType: 'AWS::EC2::VPC',
    displayName: 'VPC',
    requiredProps: ['CidrBlock'],
    connections: serviceConnectionsMap['vpc'],
  },
  {
    id: 'subnet',
    resourceType: 'AWS::EC2::Subnet',
    displayName: 'Subnet',
    requiredProps: ['VpcId', 'CidrBlock'],
    connections: serviceConnectionsMap['subnet'],
  },
  {
    id: 'nat-gateway',
    resourceType: 'AWS::EC2::NatGateway',
    displayName: 'NAT Gateway',
    requiredProps: ['SubnetId', 'AllocationId'],
    connections: serviceConnectionsMap['nat-gateway'],
  },
  {
    id: 'igw',
    resourceType: 'AWS::EC2::InternetGateway',
    displayName: 'Internet Gateway',
    requiredProps: [],
    connections: serviceConnectionsMap['igw'],
  },
  {
    id: 'nacl',
    resourceType: 'AWS::EC2::NetworkAcl',
    displayName: 'Network ACL',
    requiredProps: ['VpcId'],
    connections: serviceConnectionsMap['nacl'],
  },
  {
    id: 'sg',
    resourceType: 'AWS::EC2::SecurityGroup',
    displayName: 'Security Group',
    requiredProps: ['GroupDescription', 'VpcId'],
    connections: serviceConnectionsMap['sg'],
  },

  // Phần thêm mới của Khương
  {
    id: 'cloudwatch-logs',
    resourceType: 'AWS::Logs::LogGroup',
    displayName: 'CloudWatch Logs',
    requiredProps: ['LogGroupName'],
    connections: serviceConnectionsMap['cloudwatch-logs'],
  },
  {
    id: 'cloudwatch-metric',
    resourceType: 'AWS::CloudWatch::Metric',
    displayName: 'CloudWatch Metric',
    requiredProps: ['MetricName', 'Namespace'],
    connections: serviceConnectionsMap['cloudwatch-metric'],
  },
  {
    id: 'codebuild',
    resourceType: 'AWS::CodeBuild::Project',
    displayName: 'CodeBuild Project',
    requiredProps: ['ServiceRole', 'Environment', 'Source', 'Artifacts'],
    connections: serviceConnectionsMap['codebuild'],
  },
  {
    id: 'codepipeline',
    resourceType: 'AWS::CodePipeline::Pipeline',
    displayName: 'CodePipeline',
    requiredProps: ['RoleArn', 'Stages', 'ArtifactStore'],
    connections: serviceConnectionsMap['codepipeline'],
  },
  {
    id: 'codedeploy',
    resourceType: 'AWS::CodeDeploy::Application',
    displayName: 'CodeDeploy',
    requiredProps: ['ApplicationName', 'ComputePlatform'],
    connections: serviceConnectionsMap['codedeploy'],
  },
  {
    id: 'eventbridge',
    resourceType: 'AWS::Events::Rule',
    displayName: 'EventBridge Rule',
    requiredProps: ['EventPattern', 'State'],
    connections: serviceConnectionsMap['eventbridge'],
  },
  {
    id: 'target-group',
    resourceType: 'AWS::ElasticLoadBalancingV2::TargetGroup',
    displayName: 'Target Group',
    requiredProps: ['Port', 'Protocol', 'VpcId'],
    connections: serviceConnectionsMap['target-group'],
  },
  {
    id: 'vpc-endpoint',
    resourceType: 'AWS::EC2::VPCEndpoint',
    displayName: 'VPC Endpoint',
    requiredProps: ['ServiceName', 'VpcId'],
    connections: serviceConnectionsMap['vpc-endpoint'],
  },
  {
    id: 'msk',
    resourceType: 'AWS::MSK::Cluster',
    displayName: 'Amazon MSK (Kafka)',
    requiredProps: ['ClusterName', 'KafkaVersion', 'NumberOfBrokerNodes'],
    connections: serviceConnectionsMap['msk'],
  },
]
